---
# tasks file for cb-python-sdk
- include: setup_CentOS.yml
  when: ansible_os_family == 'CentOS'

- include: setup_Ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Download pip
  script: files/get-pip.py

- name: Install Couchbase SDK
  pip: name=couchbase
