---
#CentOS related setup
- name: run 'yum update' on CentOS 6.5
  shell: yum -y update
  when: ansible_distribution == 'CentOS' and "{{ ansible_distribution_version.split('.')[0] }}" == '6'

- name: install EPEL repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_distribution == 'CentOS' and "{{ ansible_distribution_version.split('.')[0] }}" == '7'

- name: download Couchbase RPMs
  get_url:
    url: http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-x86_64.rpm
    dest: /root/
  when: ansible_os_family == 'RedHat'

- name: Install Couchbase RPMs
  yum: name=couchbase-release-1.0-2-x86_64.rpm state=present
  when: ansible_os_family == 'RedHat'

- name: Download pre-required packages for CentOS
  yum: name={{item}} state=present
  with_items:
   - libcouchbase-devel
   - gcc
   - gcc-c++
   - python-devel
  when: ansible_os_family == 'RedHat'